/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as StakingRouteImport } from './routes/staking'
import { Route as SendRouteImport } from './routes/send'
import { Route as LendingRouteImport } from './routes/lending'
import { Route as DcaRouteImport } from './routes/dca'
import { Route as BridgeRouteImport } from './routes/bridge'
import { Route as IndexRouteImport } from './routes/index'

const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const StakingRoute = StakingRouteImport.update({
  id: '/staking',
  path: '/staking',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const LendingRoute = LendingRouteImport.update({
  id: '/lending',
  path: '/lending',
  getParentRoute: () => rootRouteImport,
} as any)
const DcaRoute = DcaRouteImport.update({
  id: '/dca',
  path: '/dca',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgeRoute = BridgeRouteImport.update({
  id: '/bridge',
  path: '/bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bridge': typeof BridgeRoute
  '/dca': typeof DcaRoute
  '/lending': typeof LendingRoute
  '/send': typeof SendRoute
  '/staking': typeof StakingRoute
  '/swap': typeof SwapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bridge': typeof BridgeRoute
  '/dca': typeof DcaRoute
  '/lending': typeof LendingRoute
  '/send': typeof SendRoute
  '/staking': typeof StakingRoute
  '/swap': typeof SwapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bridge': typeof BridgeRoute
  '/dca': typeof DcaRoute
  '/lending': typeof LendingRoute
  '/send': typeof SendRoute
  '/staking': typeof StakingRoute
  '/swap': typeof SwapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bridge'
    | '/dca'
    | '/lending'
    | '/send'
    | '/staking'
    | '/swap'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bridge' | '/dca' | '/lending' | '/send' | '/staking' | '/swap'
  id:
    | '__root__'
    | '/'
    | '/bridge'
    | '/dca'
    | '/lending'
    | '/send'
    | '/staking'
    | '/swap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BridgeRoute: typeof BridgeRoute
  DcaRoute: typeof DcaRoute
  LendingRoute: typeof LendingRoute
  SendRoute: typeof SendRoute
  StakingRoute: typeof StakingRoute
  SwapRoute: typeof SwapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staking': {
      id: '/staking'
      path: '/staking'
      fullPath: '/staking'
      preLoaderRoute: typeof StakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lending': {
      id: '/lending'
      path: '/lending'
      fullPath: '/lending'
      preLoaderRoute: typeof LendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dca': {
      id: '/dca'
      path: '/dca'
      fullPath: '/dca'
      preLoaderRoute: typeof DcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridge': {
      id: '/bridge'
      path: '/bridge'
      fullPath: '/bridge'
      preLoaderRoute: typeof BridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BridgeRoute: BridgeRoute,
  DcaRoute: DcaRoute,
  LendingRoute: LendingRoute,
  SendRoute: SendRoute,
  StakingRoute: StakingRoute,
  SwapRoute: SwapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
